package org.momentum.enums;

public enum ConversationState {

    IDLE,

    WAITING_FOR_TASK_TITLE,

    EDITING_TASK,

    WAITING_FOR_CATEGORY_TITLE,

    EDITING_CATEGORY,

    WAITING_FOR_TASK_ESTIMATED_MINUTES,

    WAITING_FOR_TASK_CATEGORY,

    WAITING_FOR_TASK_COMMENT
}